Repository youth-gallery/youth-gallery, pull requests merged in 2022-07, with the labels that each got.

#1 Fix: 에러코드 삭제 및 이미지 추가
  src/assets/Google__G__Logo 1.png
  src/assets/basic-profile-img-.png
  src/assets/basic-profile.png
  src/assets/facebook.png
  src/assets/iccon-img-layers.png
  src/assets/icon- more-vertical.png
  src/assets/icon-arrow-left.png
  src/assets/icon-edit.png
  src/assets/icon-heart.png
  src/assets/icon-home-fill.png
  src/assets/icon-home.png
  src/assets/icon-image.png
  src/assets/icon-message-circle-1.png
  src/assets/icon-message-circle-fill.png
  src/assets/icon-message-circle.png
  src/assets/icon-post-album-off.png
  src/assets/icon-post-album-on.png
  src/assets/icon-post-list-off.png
  src/assets/icon-post-list-on.png
  src/assets/icon-search.png
  src/assets/icon-share.png
  src/assets/icon-user-fill.png
  src/assets/icon-user.png
  src/assets/img-button.png
  src/assets/message-circle.png
  src/assets/s-icon-more-vertical.png
  src/assets/upload-file.png
  src/assets/x.png
  src/components/index.jsx
  src/index.js
  src/pages/index.jsx
Labels: bug, documentation

#4 DesignCSS: tabMenu UI
  src/components/tab/TapMenu.jsx
Labels: css, Html

#5 DesignCSS: topBasicNav UI
  src/components/nav/TopBasicNav.jsx
Labels: css, Html

#6 DesignCSS: topMainNav UI
  src/components/nav/TopMainNav.jsx
Labels: css, Html

#7 DesignCSS: topSearchNav UI
  src/components/nav/TopSearchNav.jsx
Labels: css, Html

#8 DesignCSS: topUploadNav UI
  src/components/nav/TopUploadNav.jsx
Labels: css, Html

#9 DesignCSS: 댓글창 UI 작업, HomePost UI 작업, HomePostOnlyTxt UI 작업
  src/assets/post-sample-image.png
  src/components/Comment.jsx
  src/components/HomePost.jsx
  src/components/HomePostOnlyTxt.jsx
Labels: css, Html

#11 DesignCSS: DeleteAlert UI 작업, Product UI 작업, UserSearch UI 작업
  src/components/DeleteAlert.js
  src/components/Product.js
  src/components/UserSearch.js
Labels: css, Html

#13 DesignCSS: UserFollow UI 작업
  src/components/UserFollow.js
Labels: css, Html

#15 Docs: PULL REQUEST Template 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#16 DesignCSS(TopBasicNav.jsx): 스타일드 컴포넌트 세분화하여 태그별 스타일 분리 적용
  src/components/nav/TopBasicNav.jsx
Labels: css

#17 DesignCSS(TopSearchNav.jsx): 스타일드 컴포넌트 세분화하여 태그별 스타일 분리 적용
  src/components/nav/TopSearchNav.jsx
Labels: css

#18 DesignCSS(TopMainNav.jsx): 스타일 컴포넌트를 태그별로 나누어 분리 후 적용
  src/components/nav/TopMainNav.jsx
Labels: css

#19 DesignCSS(TopUploadNav.jsx): 스타일드 컴포넌트 세분화하여 태그별 스타일 분리 적용
  src/components/nav/TopUploadNav.jsx
Labels: css

#20 Feat: 하단 탭 아이콘을 누르면 아이콘 색 변경 및 페이지 이동 구현
  src/components/tab/TapMenu.jsx
  src/components/tab/TapMenuMove.jsx
Labels: css, function

#23 DeginCSS: navbar와 메뉴탭에 구분을 위한 회색 테두리 추가
  src/components/nav/TopBasicNav.jsx
  src/components/nav/TopMainNav.jsx
  src/components/nav/TopSearchNav.jsx
  src/components/nav/TopUploadNav.jsx
  src/components/tab/TapMenu.jsx
Labels: css

#24 DesignCSS: reset.css에 필요한 css 추가
  src/styles/reset.css
Labels: css

#25 Feat: modal UI 구성 및 페이지 이동 링크 연결(예비 링크)
  src/components/modal/LoginModal.jsx
  src/components/modal/LoginModal.module.css
  src/components/modal/Modal.jsx
  src/components/modal/Modal.module.css
  src/components/modal/PostModal.jsx
  src/components/modal/PostModal.module.css
Labels: css, function

#28 Feat: 팔로워 리스트 기능 추가 ...
  src/components/UserFollow.js
  src/components/nav/TopBasicNav.jsx
  src/components/tab/TapMenu.jsx
  src/components/tab/TapMenuMove.jsx
  src/pages/FollowersList.jsx
  src/pages/FollowersList.module.css
Labels: css, function

#34 Chore: eslint.json, package.json 업데이트
  .eslintrc.json
  package.json
  src/styles/global.css
Labels: chore

#26 Feat: 게시물 작성 최종
  public/index.html
  src/components/PostForm/PostForm.jsx
  src/components/PostForm/PostForm.module.css
  src/components/nav/TopUploadNav.jsx
  src/font.css
  src/pages/postUpload/PostUpload.jsx
  src/pages/postUpload/PostUploadForm.jsx
  src/pages/postUpload/PostUploadForm.module.css
  src/pages/postUpload/PostUploadTest.jsx
Labels: function

#32 Feat: 팔로윙 리스트 기능 추가 ...
  src/components/UserFollow.js
  src/components/button/SearchCancelButton.jsx
  src/components/tab/TapMenuMove.jsx
  src/pages/FollowingsList.jsx
  src/pages/FollowingsList.module.css
Labels: css, function

#30 Feat: 개인 프로필 기능 추가 및 스타일 변경 ...
  src/components/Product.js
  src/components/Profile.jsx
  src/components/Profile.module.css
  src/components/UserPost.jsx
  src/pages/userprofile/UserProfile.jsx
  src/pages/userprofile/UserProfile.module.css
Labels: css, Html, function

#35 DesignCSS: 반응형 시 버튼 컴포넌트 깨지는 부분 수정
  .eslintrc.json
  package-lock.json
  src/App.js
  src/components/LoginInput.jsx
  src/components/button/FollowButton.jsx
  src/components/button/FollowDisabledButton.jsx
  src/components/button/NextButton.jsx
  src/components/button/NextDisabledButton.jsx
  src/components/button/SaveButton.jsx
  src/components/button/SaveDisabledButton.jsx
  src/components/button/SearchCancelButton.jsx
  src/components/button/SearchFollowButton.jsx
  src/components/button/UnFollowButton.jsx
  src/components/login/EmailJoin.jsx
  src/components/login/EmailJoin.module.css
  src/components/login/Login.jsx
  src/components/login/Login.module.css
  src/components/login/Splash.jsx
  src/components/login/Splash.module.css
  src/components/login/Title.jsx
  src/components/login/Title.module.css
  src/font.css
  yarn.lock
Labels: css, fix

#36 Feat: 로그인 화면 UI 추가
  src/components/login/Login.jsx
  src/components/login/Login.module.css
  src/components/login/Title.module.css
Labels: css

#37 Feat: 이메일로 로그인, 프로필 설정 UI 추가
  src/components/LoginInput.jsx
  src/components/join/EmailJoin.jsx
  src/components/join/EmailJoin.module.css
  src/components/login/EmailJoin.jsx
  src/components/login/EmailJoin.module.css
  src/components/membership/JoinMembership.jsx
  src/components/membership/JoinMembership.module.css
Labels: css

#42 Refactor: Navbar 합성 컴포넌트로 리팩토링
  src/components/button/SaveButton.jsx
  src/components/nav/Nav.jsx
  src/components/nav/TopBasicNav.jsx
  src/components/nav/TopMainNav.jsx
  src/components/nav/TopSearchNav.jsx
  src/components/nav/TopUploadNav.jsx
Labels: refactoring

#40 DesignCSS: 상품 등록 페이지 UI 구현
  src/pages/addProduct/AddProduct.jsx
  src/pages/addProduct/AddProduct.module.css
Labels: css, Html

#48 Feat: 미술계 소식 페이지 추가
  .eslintrc.json
  src/pages/news/News.jsx
  src/pages/news/NewsCard.jsx
  src/pages/news/NewsCard.module.css
  src/pages/news/NewsList.jsx
  src/pages/news/NewsList.module.css
Labels: function

#50 Feat: 팔로우 없을 때, 404에러 페이지 제작
  src/pages/NonFollowing.jsx
  src/pages/NotFound.jsx
  src/pages/PageRouter.jsx
Labels: css, function

#52 Feat: 이미지 미리보기 기능 추가
  src/pages/addProduct/AddProduct.jsx
  src/pages/addProduct/AddProduct.module.css
Labels: css, function

#54 Feat: 프로필설정 사진 미리보기 기능 추가, Fix: 프로필설정 사진첨부 input type="file"로 변경
  src/components/membership/JoinMembership.jsx
  src/components/membership/JoinMembership.module.css
Labels: css, fix, function

#51 Feat: 게시물 상세 페이지 연결 테스트
  src/components/HomePost.jsx
  src/components/comment/CommentList.jsx
  src/pages/Home.jsx
  src/pages/PageRouter.jsx
  src/pages/postDetail/PostDetail.jsx
Labels: function

#55 Feat: 게시물 내용 또는 사진 첨부시 버튼색 변동
  src/components/PostForm/PostForm.module.css
  src/components/button/SaveDisabledButton.jsx
  src/components/nav/TopUploadNav.jsx
  src/pages/PageRouter.jsx
  src/pages/postUpload/PostUploadForm.jsx
  src/pages/postUpload/PostUploadForm.module.css
Labels: css, function

#59 Fix: PageRouter 파일에 profile path 중복 수정
  src/pages/PageRouter.jsx
Labels: bug

#57 Feat:로그인 버튼 활성화 기능 추가 , Fix: label태그로 변경, styled-component 변수이름 변경
  src/components/LoginInput.jsx
  src/components/join/EmailJoin.jsx
  src/components/join/EmailJoin.module.css
  src/components/login/Login.jsx
  src/components/login/Login.module.css
  src/components/membership/JoinMembership.jsx
  src/components/membership/JoinMembership.module.css
Labels: css, Html, fix, function

#58 Feat: 검색 시 일치하는 문자 배경색 변경 및 검색결과 없음 문구 추가
  src/components/UserSearch.jsx
  src/pages/Search.jsx
Labels: css, function

#56 Refactor: 모달 기능 모듈화 작업 및 적용
  src/components/HomePost.jsx
  src/components/UserPost.jsx
  src/components/modal/ButtonModal.jsx
  src/components/modal/ButtonModalActive.jsx
  src/components/modal/InnerAlert.jsx
  src/components/modal/PostModal.jsx
  src/components/nav/TopBasicNav.jsx
  src/pages/userprofile/UserProfile.jsx
  src/pages/userprofile/UserProfile.module.css
Labels: function, refactoring

#65 Feat: 로그인 기능구현
  src/components/login/Login.jsx
  src/components/login/Login.module.css
Labels: function

#60 Feat: 상품등록 기능 추가
  src/pages/addProduct/AddProduct.jsx
Labels: function

#61 Feat: 팔로우 기능 추가
  src/components/button/FollowButton.jsx
Labels: function

#62 Feat: 언팔로우 기능 추가
  src/components/button/UnFollowButton.jsx
Labels: function

#63 Fix: 내 프로필일 때 버튼 추가
  src/components/Profile.jsx
  src/components/Profile.module.css
Labels: function

#67 Feat: 뉴스 페이지 연결
  src/pages/PageRouter.jsx
  src/pages/news/News.jsx
Labels: React

#68 Fix: 상품등록 이미지 에러 핸들링
  src/pages/addProduct/AddProduct.jsx
Labels: fix, function

#70 DesignCSS: 상품리스트 width값 설정, 가운데 정렬
  src/components/Product.js
  src/components/Profile.module.css
  src/pages/userprofile/UserProfile.jsx
  src/pages/userprofile/UserProfile.module.css
Labels: css

#69 Feat: 페이지 라우터 Splash 링크 연결, background-color 변경, + 로그인 성공시 홈피드로 이동 (추가)
  src/components/login/Login.jsx
  src/components/login/Login.module.css
  src/components/login/Splash.jsx
  src/components/login/Splash.module.css
  src/pages/PageRouter.jsx
Labels: React, function

#72 Feat: 게시물 삭제 기능 추가
  src/components/UserPost.jsx
Labels: function

#71 Feat: 댓글 모달 추가 및 location을 활용한 게시글 이동 추가
  src/components/HomePost.jsx
  src/components/HomePostOnlyTxt.jsx
  src/components/PostForm/HomePost.jsx
  src/components/PostForm/HomePostOnlyTxt.jsx
  src/components/PostForm/PostAuthorInfo.jsx
  src/components/PostForm/PostComment.jsx
  src/components/PostForm/PostDate.jsx
  src/components/PostForm/PostHeartBtn.jsx
  src/components/PostForm/PostImg.jsx
  src/components/comment/Comment.jsx
  src/components/comment/CommentBox.jsx
  src/components/comment/CommentList.jsx
  src/components/modal/ButtonModal.jsx
  src/pages/Home.jsx
  src/pages/PageRouter.jsx
  src/pages/postDetail/PostDetail.jsx
Labels: function

#74 Fix: 로그인 성공시 로컬스토리지에 유저네임 저장
  src/components/login/Login.jsx
Labels: fix, function

#75 Feat: 개인 프로필 연결 링크변경 및 게시물 좋아요 댓글 상세페이지 기능 추가
  src/components/UserPost.jsx
  src/components/tab/TabMenu.jsx
  src/pages/Home.jsx
  src/pages/PageRouter.jsx
Labels: function, refactoring

#81 Feat: 홈 피드에 '유저를 검색해 팔로우 해보세요' 페이지 표시
  src/pages/Home.jsx
Labels: function

#76 Feat: post 앨범형, 리스트형 변환 기능 구현 , 고정값 로그인 된 정보로 변경 ...
  src/components/Profile.jsx
  src/pages/userprofile/UserProfile.jsx
  src/pages/userprofile/UserProfile.module.css
Labels: css, function

#83 Feat: 검색 후 선택한 사용자 클릭 시 프로필로 이동
  src/components/modal/PostModal.jsx
  src/pages/Search.jsx
  src/pages/userprofile/UserProfile.jsx
Labels: function

#84 Fix: 버튼이 활성화 상태일 때만 상품등록 데이터 전송, 고정값 변경
  src/pages/addProduct/AddProduct.jsx
Labels: function

#85 Fix: 댓글 작성자 토큰 삭제 및 정보 받아오기 수정
  src/components/comment/Comment.jsx
  src/components/comment/CommentList.jsx
Labels: fix

#87 Rename: Profile 을 UserInfo로 변경, Fix: 내 계정과 타인 계정 버튼 다르게 나타내기 실제 작동
  src/components/UserInfo.jsx
  src/components/UserInfo.module.css
  src/pages/userprofile/UserProfile.jsx
Labels: function

#78 Feat: 이메일 회원가입 기능 추가, Fix: 로그인 마운트시 경고문구 삭제 + 페이지라우터 프로필설정 추가 + Fix: 회원가입 경고문구 수정
  src/components/join/EmailJoin.jsx
  src/components/join/EmailJoin.module.css
  src/components/login/Login.jsx
  src/pages/PageRouter.jsx
Labels: fix, function

#89 Feat: 프로필설정 기능추가 (진행중), Fix: 전역으로 반영되는 module css 태그 제거
  src/components/join/EmailJoin.jsx
  src/components/join/EmailJoin.module.css
  src/components/login/Login.jsx
  src/components/login/Login.module.css
  src/components/membership/JoinMembership.jsx
  src/components/membership/JoinMembership.module.css
Labels: function

#92 Fix: 프로필설정 module.css 클래스네임 수정
  src/components/membership/JoinMembership.jsx
  src/components/membership/JoinMembership.module.css
Labels: fix

#94 Fix: 로그인, 회원가입 module.css 클래스네임 변경
  src/components/join/EmailJoin.jsx
  src/components/join/EmailJoin.module.css
  src/components/login/Login.jsx
  src/components/login/Login.module.css
Labels: fix

#96 Feat: 홈 게시물에서 이미지 깨질 시 기본 이미지 세팅
  src/assets/ImageNotFound.png
  src/components/PostForm/PostImg.jsx
Labels: function

#99 DesignCSS: 마이프로필 배경 수정
  src/pages/userprofile/UserProfile.module.css
Labels: css

#101 Feat: 프로필설정 유효성검사, 중복검사 추가, DesignCSS: 로그인 회원가입 css수정
  src/components/join/EmailJoin.module.css
  src/components/login/Login.module.css
  src/components/membership/JoinMembership.jsx
  src/components/membership/JoinMembership.module.css
Labels: css, function

#105 Feat: 프로필설정 유효성검사 모두 통과시 버튼활성화 기능추가
  src/components/membership/JoinMembership.jsx
Labels: function

#106 Fix: 팔로워리스트 account값 오류 수정
  src/pages/FollowersList.jsx
Labels: fix

#108 Fix: 팔로윙리스트 고정값 수정 및 Nav 추가
  src/pages/FollowingsList.jsx
Labels: fix

#110 DesignCSS: 검색 상태별 표시 디자인 변경
  src/assets/brush.png
  src/assets/palette.png
  src/components/search/NonSearch.jsx
  src/components/search/RecomendSearch.jsx
  src/components/search/ShowSearch.jsx
  src/components/search/UserSearch.jsx
  src/pages/Search.jsx
Labels: css

#91 Feat: 댓글 삭제 기능 추가
  src/components/PostForm/HomePostOnlyTxt.jsx
  src/components/UserPost.jsx
  src/components/comment/CommentBox.jsx
  src/components/comment/CommentList.jsx
  src/components/modal/ButtonModalActive.jsx
  src/hooks/useComments.jsx
  src/pages/postDetail/PostDetail.jsx
Labels: function

#112 Fix: 게시물 작성시 로그인한 프로필로 나오도록 수정
  src/components/PostForm/PostForm.jsx
Labels: function

#113 Feat: 게시물 프로필 이름 누를 시 프로필 페이지 이동
  src/components/PostForm/HomePost.jsx
  src/components/PostForm/PostAuthorInfo.jsx
Labels: function

#114 DesignCSS: 홈 배경 스트롤 수정
  src/pages/Home.jsx
Labels: css

#115 Fix/게시물 수정 페이지 404로 뜨는 문제 해결, 수정시 사진이 없을 때 빈 사진 뜨는 문제 해결
  src/components/UserPost.jsx
  src/components/modal/ButtonModalActive.jsx
  src/components/modal/PostModal.jsx
  src/pages/PageRouter.jsx
  src/pages/postEdit/PostEdit.jsx
Labels: bug

#117 DesignCSS: 게시물 상세 배경 변경
  src/components/comment/Comment.jsx
  src/pages/postDetail/PostDetail.jsx
Labels: css

#118 Feat: 회원가입 데이터전달을 위해 프로필설정 컴포넌트 숨겨주기, 프로필설정 이미지 데이터 전달(진행중)
  src/components/join/EmailJoin.jsx
  src/components/membership/JoinMembership.jsx
Labels: function

#119 DesignCSS: 회원가입 프로필설정 배경 수정
  src/components/join/EmailJoin.module.css
  src/components/membership/JoinMembership.module.css
Labels: css

#122 Fix: 댓글 작성시 재렌더링 안되는 부분 수정
  src/components/comment/Comments.jsx
  src/components/comment/Comments.module.css
  src/pages/postDetail/PostDetail.jsx
Labels: fix

#123 Fix: 회원가입, 프로필설정 기능구현 (수정중)
  src/components/join/EmailJoin.jsx
  src/components/membership/JoinMembership.jsx
Labels: fix

#125 Feat: 로그아웃 기능 구현
  src/pages/userprofile/UserProfile.jsx
Labels: function

#126 Fix: 유저프로필 팔로윙 오류 해결
  src/components/UserInfo.jsx
Labels: fix

#128 DesignCSS: myprofile이외의 BasicNav에서 모달 버튼 숨김
  src/components/nav/TopBasicNav.jsx
Labels: css

#129 DesignCSS: 게시물 상세 댓글 너비 조정
  src/components/comment/Comments.module.css
Labels: css

#131 DesignCSS: 소식 페이지 배경 수정
  src/pages/news/NewsList.module.css
Labels: css

#132 DesignCSS: 게시물 수정 페이지 배경 변경
  src/pages/addProduct/AddProduct.jsx
  src/pages/addProduct/AddProduct.module.css
  src/pages/postEdit/PostEdit.jsx
  src/pages/postEdit/PostEdit.module.css
Labels: css

#135 DesignCSS: textarea 영역 수정
  src/pages/postUpload/PostUploadForm.jsx
  src/pages/postUpload/PostUploadForm.module.css
Labels: React

#143 Fix: 이미지 클릭시게시글 상세로 이동하는 기능 삭제
  src/components/UserPost.jsx
Labels: bug

#144 Fix: 유저프로필 Nav바 문구 삭제
  src/pages/userprofile/UserProfile.jsx
Labels: fix

#146 Fix: 상세페이지 고정 토큰 삭제
  src/pages/postEdit/PostEdit.jsx
Labels: bug

#147 Fix: 타인 계정 게시글 점 세개 버튼 클릭 시 신고하기로 변경
  src/components/UserPost.jsx
Labels: fix

#150 Refactor: 라우터 수정
  src/components/login/Login.jsx
  src/components/tab/TabMenu.jsx
  src/pages/PageRouter.jsx
  src/pages/userprofile/UserProfile.jsx
Labels: refactoring

#151 Fix: 유저포스트 수정
  src/components/UserPost.jsx
  src/pages/postEdit/PostEdit.jsx
  src/pages/postEdit/PostEdit.module.css
Labels: css, fix

#152 Fix: UseReport import 방식 수정
  src/components/UserPost.jsx
Labels: fix

#154 DesignCSS: x 버튼 위치 수정
  src/pages/postUpload/PostUploadForm.module.css
Labels: css

#157 DesignCSS: 게시물 작성 미리보기 이미지 스크롤 추가
  src/pages/postUpload/PostUploadForm.module.css
Labels: css

#158 DesingCSS: textarea 영역 사이즈 수정
  src/pages/postEdit/PostEdit.module.css
  src/pages/postUpload/PostUploadForm.module.css
Labels: css

#159 DesignCSS: 홈 피드 게시물 보여지는 방식 변경
  src/components/loding/Styles.jsx
  src/pages/Home.jsx
  src/pages/Search.jsx
Labels: css

#160 Fix: 검색을 하고 빠르게 선택하지 않으면 리스트가 변경되는 에러 해결
  src/components/search/ShowSearch.jsx
  src/pages/Search.jsx
Labels: bug

#161 Fix: nav 뒤로가기 버튼 누를 시 이전페이지가 아닌 홈으로 이동
  src/components/nav/TopBasicNav.jsx
  src/components/nav/TopUploadNav.jsx
Labels: UX

#162 Feat: 상품 수정 기능 추가
  src/components/Product.js
  src/components/modal/PostModal.jsx
  src/pages/PageRouter.jsx
  src/pages/productEdit/ProductEdit.jsx
Labels: function

#163 Feat: 프로필 수정 클릭시 수정페이지로 이동
  src/components/UserInfo.jsx
  src/components/membership/JoinMembership.jsx
  src/pages/PageRouter.jsx
Labels: function

#164 DesignCSS: 게시물 수정 이미지 추가 버튼 이동 및 게시물 게시날짜로 변경
  src/components/PostForm/HomePost.jsx
  src/components/PostForm/PostDate.jsx
  src/hooks/useCommentsCount.jsx
  src/pages/postEdit/PostEdit.module.css
Labels: bug, css, UX

#165 Feat: 프로필수정 폴더 추가
  src/components/editProfile/EditProfile.jsx
  src/components/editProfile/EditProfile.module.css
Labels: chore

#167 Fix: 페이지라우터 EditProfile 경로변경, UserProfile myprofile로변경
  src/pages/PageRouter.jsx
Labels: fix

#168 Fix: 내 계정은 무조건 myprofile로 이동
  src/pages/userprofile/UserProfile.jsx
Labels: fix

#169 Fix: 타인 프로필에서 내 프로필로 가면 버튼만 바뀌던 오류 해결
  src/pages/userprofile/UserProfile.jsx
Labels: fix

#172 Fix: TopBasicNav에 UseLocation 추가
  src/components/nav/TopBasicNav.jsx
Labels: fix

#176 Fix: 게시물 상세 댓글 변화 감지 에러 해결
  src/components/PostForm/PostComment.jsx
  src/components/PostForm/PostHeartBtn.jsx
  src/components/comment/Comment.jsx
  src/components/comment/CommentBox.jsx
  src/components/comment/CommentList.jsx
  src/components/comment/Comments.jsx
  src/hooks/useCommentsCount.jsx
  src/pages/postDetail/PostDetail.jsx
Labels: bug

#177 Feat: 마이프로필 수정 내기존정보 불러오기 (사진추가중)
  src/components/UserInfo.jsx
  src/components/editProfile/EditProfile.jsx
  src/components/join/EmailJoin.jsx
Labels: function

#178 Style: global.css 성공시 초록색 색상 추가
  src/styles/global.css
Labels: css

#179 Fix: 상품 등록, 상품 수정 초기 값 변경
  src/pages/addProduct/AddProduct.jsx
  src/pages/productEdit/ProductEdit.jsx
Labels: fix

#180 DesignCSS: 홈 여백 조정
  src/components/PostForm/HomePost.jsx
  src/pages/Home.jsx
Labels: css

#182 DesignCSS: 사용가능한 이메일 메시지 띄울 시 색깔 변경
  src/components/join/EmailJoin.jsx
  src/components/join/EmailJoin.module.css
Labels: css

#183 DesignCSS: 프로필설정 사용가능한 계정ID일 시에 색상 변경
  src/components/membership/JoinMembership.jsx
  src/components/membership/JoinMembership.module.css
Labels: css

#184 Feat: 마이프로필 수정 기능추가
  src/components/UserInfo.jsx
  src/components/editProfile/EditProfile.jsx
  src/components/editProfile/EditProfile.module.css
Labels: function

#185 DesignCSS: 마이프로필 프로필사진 크기 수정
  src/components/editProfile/EditProfile.module.css
Labels: css

#187 Docs: 리드미 수정
  README.md
Labels: docs

#191 Fix: 마이프로필 수정 버튼 활성화 수정 (추후 좀더 수정)
  src/components/editProfile/EditProfile.jsx
Labels: fix

#192 Fix: 마이프로필 수정에서 로컬스토리지에 accountname 저장
  src/components/editProfile/EditProfile.jsx
Labels: fix

#193 Style: 스플래쉬 폴더 생성, SplashBase 파일 생성, 페이지라우터 임포트 변경
  src/components/login/Splash.jsx
  src/components/login/Splash.module.css
  src/pages/PageRouter.jsx
Labels: chore

#194 Feat: splash 애니메이션 개선
  src/pages/PageRouter.jsx
Labels: css

#195 DesignCSS: splash 애니메이션 수정
  src/components/splash/Splash.jsx
  src/components/splash/Splash.module.css
  src/components/splash/SplashBase.jsx
  src/components/splash/SplashBase.module.css
Labels: css
